---
 title: "Trees demography"
 subtitle: "Bayesian models to predict trees vital rates"
 author: "Will Vieira"
 date: "`r paste('Last updated on', format(Sys.time(), '%d %B, %Y'))`"
---

# Tests

## Mortality

- Environment scaled ([link v1.0](https://willvieira.github.io/TreesDemography/mort/envirScaled.html))

- Bernoulli vectorized ([link v2.0](https://willvieira.github.io/TreesDemography/mort/bernVectorized.html))

- Growth rate effect ([link v3.0](https://willvieira.github.io/TreesDemography/mort/growthRateEffect.html), [link v3.1](https://willvieira.github.io/TreesDemography/mort/growthRateEffect2.html))

- Canopy continuous ([link v4.0](https://willvieira.github.io/TreesDemography/mort/canopyContinuous.html))

- Basal area ([link v5.0](https://willvieira.github.io/TreesDemography/mort/basalArea.html))

- Constrained parameters ([link v6.0](https://willvieira.github.io/TreesDemography/mort/constrainedPars.html))

- Competition (canopy distance vs basal area - ([link v7.0](https://willvieira.github.io/TreesDemography/mort/competition.html))

- Plot random effects on baseline longevity (psi) - ([link v8.0](https://willvieira.github.io/TreesDemography/mort/randomEffect_plot.html))

- Year random effects on baseline longevity (psi) - ([link v8.0](https://willvieira.github.io/TreesDemography/mort/randomEffect_year.html))

## Growth

- Competition (canopy distance vs basal area - ([link v1.0](https://willvieira.github.io/TreesDemography/growth/competition.html))

- Competition (different parameters set - ([link v2.0](https://willvieira.github.io/TreesDemography/growth/ba_pars.html))

- Competition function (linear vs half-normal function - ([link v3.0](https://willvieira.github.io/TreesDemography/growth/linearVShalf.html))

- Competition function as a function of both Basal area and canopyDistance ([link v4.0](https://willvieira.github.io/TreesDemography/growth/BAandCD.html))

- Competition function as a function of both Basal area and canopyDistance ([link v5.0](https://willvieira.github.io/TreesDemography/growth/BAandCD2.html))

- Random effect on the baseline growth rate (pdg) ([link v6.0](https://willvieira.github.io/TreesDemography/growth/randomEffect.html))

- Canopy distance vs basal area with random effect ([link v7.0](https://willvieira.github.io/TreesDemography/growth/compPredictor.html))

- Canopy distance with different parameters set ([link v8.0](https://willvieira.github.io/TreesDemography/growth/canopyDistanceFun.html))

- Canopy distance with different parameters set and new dataset ([link v8.1](https://willvieira.github.io/TreesDemography/growth/canopyDistanceFunB.html))

- Canopy distance with 3 parameters vs basal area ([link v9.0](https://willvieira.github.io/TreesDemography/growth/BAvsCanopy.html))

- Von Bertalanffy intercept model with parametric starting size ([link v10.0](https://willvieira.github.io/TreesDemography/growth/bertalanffy_intercept.html))

- Von Bertalanffy intercept model with data starting size ([link v11.0](https://willvieira.github.io/TreesDemography/growth/bertalanffyInt_startSize.html))

- Von Bertalanffy intercept model with measurement error in starting size ([link v12.0](https://willvieira.github.io/TreesDemography/growth/bertalanffyInt_startSize_par.html))

- Von Bertalanffy intercept model with data starting size and plot random effects on `r` ([link v13.0](https://willvieira.github.io/TreesDemography/growth/bertalanffyInt_randomPlot.html))

- Von Bertalanffy model with basal area fixed effect and  plot random effects on `r` ([link v14.0](https://willvieira.github.io/TreesDemography/growth/bertalanffy_BA.html))

- Von Bertalanffy model with basal area fixed effect (sigmoid function instead of exponential) and  plot random effects on `r` ([link v15.0](https://willvieira.github.io/TreesDemography/growth/bertalanffy_BA_sigmoid.html))

- Von Bertalanffy model v14.0 but using previous measurement as starting size ([link v16.0](https://willvieira.github.io/TreesDemography/growth/bertalanffy_BA_st.html))

- Von Bertalanffy model v16.0 but using the RESEF dataset ([link v16.1](https://willvieira.github.io/TreesDemography/growth/bertalanffy_BA_st_resef.html))

- Von Bertalanffy model v16.0 with plot + individual random effects ([link v17.0](https://willvieira.github.io/TreesDemography/growth/bertalanffy_BA_st_randomInd.html))

- Von Bertalanffy model v16.0 with `r` varying in function of basal area and mean annual temperature  ([link v18.0](https://willvieira.github.io/TreesDemography/growth/bertalanffy_BA_st_temp.html))

- Von Bertalanffy model v18.0 with basal area, mean annual temperature, and mean annual precipitation effect ([link v19.0](https://willvieira.github.io/TreesDemography/growth/bertalanffy_BA_st_tempPrec.html))

- Vanderwel version 9.0 with new dataset ([link v20.0](https://willvieira.github.io/TreesDemography/growth/Vanderwel_BA_tempPrec.html))

## Recruitment

- Fast transition - ([link v1.0](https://willvieira.github.io/TreesDemography/recruit/fastTransition.html))

- Ingrowth intercept - ([link v2.0](https://willvieira.github.io/TreesDemography/recruit/intercept.html))

- Ingrowth intercept with plot random effects on `m` (ingrowth rate) - ([link v3.0](https://willvieira.github.io/TreesDemography/recruit/rec_m_randomPlot.html))

- Ingrowth with basal area fixed effects and plot random effects on `m` (ingrowth rate) - ([link v4.0](https://willvieira.github.io/TreesDemography/recruit/rec_m_randomPlot_BA.html))

- Ingrowth v4.0 but using the RESEF dataset - ([link v4.1](https://willvieira.github.io/TreesDemography/recruit/rec_m_randomPlot_BA_resef.html))

- Version 4.0 with an additional parameter to account for immigration - ([link v5.0](https://willvieira.github.io/TreesDemography/recruit/rec_m_BA_imm.html))

- Ingrowth where ingrowth rate `m` is affected by basal are of conspecific species (seed source) and mortality rate `p` affected by the total basal area - ([link v6.0](https://willvieira.github.io/TreesDemography/recruit/rec_m_p_BA.html))

- Version 4.0 but using the negative binomial instead of the possion distribution in the likelihood - ([link v7.0](https://willvieira.github.io/TreesDemography/recruit/rec_m_rp_BA_nbinom.html))

- Version 4.0 with zero inflated theta paramter - ([link v8.0](https://willvieira.github.io/TreesDemography/recruit/rec_m_rp_BA_zeroInflated.html))

- Version 5.0 with unimodal function to model the effect of BA_sp on `m` and negative exponential function to model the effect of BA_plot on `p` ([link v10.0](https://willvieira.github.io/TreesDemography/recruit/rec_m_p_BA_v2.html))
