---
 title: "MCMC diagnostics - Mortality"
 subtitle: "Test v1.0 - enviroment scaled"
 author: "Will Vieira"
 date: "`r paste('Last updated on', format(Sys.time(), '%d %B, %Y'))`"
---

```{r, echo = F}
###############################
# Automate MCMC diagnostics for all species and compite in a pdf report
# Will Vieira
# March 18, 2019
##############################

##############################
# Steps:
  # Load simulation variables
  # Load rStan output for all species_id
  # Diagnostics:
    # Rhat for each parameter and each species
    # Density plot for each parameter and species
  # Plot of size, temperature, precipitation and competition effect
  # Plot predictions
##############################
```

```{r, echo = F}
suppressPackageStartupMessages(library(rstan))
suppressPackageStartupMessages(require(RColorBrewer))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(ggridges))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(DT))
```
```{r load simulations, echo = F}
# Basic functions
  # convert Temperature and precipitation
  unscale <- function(x, max, min) return (x*(max - min) + min)
  unscaleSD <- function(x, max, min) return (x*(max - min))
#


# Load simulation variables
  simInfo <- yaml::read_yaml('_simulation_info.yml')

  # species id
  if(is.null(simInfo$spIds)) {
    spIds <- readRDS('data/spIds.RDS')
  }else {
    spIds <- simInfo$spIds
  }

  simName <- simInfo$simName

  simulations <- simInfo$simulations

  # Human readble simName
  sim1name <- 'Sim1: env scaled'
  sim2name <- 'Sim2: env not scaled'

#

# Load rStan output and scaleInfo for all species_id
  # get output name for each species_id
  simNames = list.files(path = 'output/', pattern = '.RDS', recursive = TRUE, full.names = TRUE)
  output = simNames[grep('mortMCMC', simNames)]
  scale = simNames[grep('scaleInfo', simNames)]

  for(sim in simulations) {
    for(sp in spIds) {
      fileName <- output[grep(paste0(sim, sp), output)]
      assign(paste('fit', sim, sp, sep = '_'), readRDS(fileName))
    }
  }

  # get name of parameters for each simulation
  for(sim in simulations)
  {
    # get one MCMC file for a specific sim
    assign(paste0('pars_', sim), rownames(summary(get(ls(pattern = sim)[1]))[[1]]))
  }

#

###########################################
# Diagnostics
###########################################
```



# Rhat

```{r, echo = F, fig.height = 6, fig.width = 10}

  # number of parameters for all simulations
  nbParams <- do.call('*', lapply(as.list(paste0('pars_', simulations)), function(x) length(get(x))))
  # create a table with Rhat for each parameter (clumn) and species_id (Rhat)
  Rhat <- data.frame()
  count = 1
  for(sim in simulations) {
    for(sp  in spIds) {
      df <- summary(get(paste('fit', sim, sp, sep = '_')))$summary
      nRow = nrow(df)
      dfToAdd <- data.frame(rep(sim, nRow), rep(sp, nRow), rownames(df), df[, 'Rhat'], row.names = NULL)
      Rhat <- rbind(Rhat ,dfToAdd)
    }
  }
  names(Rhat) <- c('sim', 'sp', 'pars', 'Rhat')

  p <- ggplot(data = Rhat, aes(x = sp, y = Rhat)) +
       geom_boxplot() +
       coord_flip() +
       facet_grid(~sim,
                 labeller = labeller(sim = setNames(c(sim1name,
                                     sim2name),
                                     c('sim1', 'sim2')))) +
       theme_classic()
  print(p)
```



# Divergent transitions

```{r divergent transitions, echo = FALSE}

divergentDF <- data.frame(matrix(NA, ncol = 3))
names(divergentDF) <- c('sim', 'sp', 'divergent')

count = 1
for(sim in simulations) {
  for(sp in spIds) {
    simName <- paste('fit', sim, sp, sep = '_')
    sampler_params <- get_sampler_params(get(simName), inc_warmup = FALSE)
    nbDivergent <- sum(unlist(lapply(sampler_params, function(mat) mat[, 'divergent__'])))
    divergentDF[count, ] <- c(sim, sp, nbDivergent)
    count = count + 1
  }
}
```

```{r divergent table, echo = FALSE}
DT::datatable(divergentDF)
```



# Density plot of each parameter by species id

```{r get MCMC sampling data, echo = F}
  # Prepare data
  # Data frame with sim, sp_id, pars and value
  # Value is all MCMC samples after warmup for all chains together

  mcmcSampleDF <- data.frame()
  for(sim in simulations) {
    for(sp in spIds) {
      simObj <- get(paste('fit', sim, sp, sep = '_'))
      dfToAdd <- gather(as.data.frame(simObj), key = 'pars')
      dfToAdd <- cbind(data.frame(sim = rep(sim, nrow(dfToAdd)), sp = rep(sp, nrow(dfToAdd))), dfToAdd)
      mcmcSampleDF <- rbind(mcmcSampleDF, dfToAdd)
    }
  }
```

```{r plot mcmcSample by pars, echo = F, message=FALSE, fig.height = 7, fig.width = 9}

  for(par in unique(mcmcSampleDF$pars))
  {
    p <- ggplot(data = subset(mcmcSampleDF, pars == par), aes(value, sp)) +
         geom_density_ridges_gradient() +
         facet_grid(~sim, scales = ifelse(par %in% c("T_opt", "sigmaT_opt", "P_opt", "sigmaP_opt"), 'free_x', 'fixed'),
                   labeller = labeller(sim = setNames(c('Sim1: Env scaled',
                                       'Sim2: Env not scaled'),
                                       c('sim1', 'sim2')))) +
         theme_classic() +
         xlab(par)
    print(p)
  }
```



# Size, temperature, precipitation and competition effect

```{r, echo = F, fig.height = 13, fig.width = 9}
# Plot of size, temperature, precipitation and competition effect

  # define functions of the model
    # size effect
    sizeEffect = function(x, DBHopt, DBHvar) {
      lgPart <- (log(x/DBHopt)/DBHvar)^2
      return( exp(-lgPart))
    }
    # temperature effect
    tempEffect = function(xtemp, T_opt, sigmaT_opt) {
      return(exp(-0.5*(xtemp - T_opt)^2/sigmaT_opt^2))
    }
    # precipitation effect
    precEffect = function(xprec, P_opt, sigmaP_opt) {
      return(exp(-0.5*(xprec - P_opt)^2/sigmaP_opt^2))
    }
    # competition effect
    compEffect = function(canopy, beta) {
      return(canopy + (1 - canopy)*beta)
    }
  #

  ## PLOT ##

  # define x axis
  sizex = seq(10, 900)
  tempx = seq(-35, 20)
  precx = seq(0, 3500)

  # species specfic colours
  spCols <- rev(RColorBrewer::brewer.pal(length(spIds), "Set1"))

  par(mfrow = c(4, 2), xaxs = "i", las = 1, mar = c(3, 1, 3, 1.5), oma = c(1,3.5,2,.2), mgp = c(1.5, 0.3, 0), tck = -.008, cex.lab = 1.2, cex.axis = 1.2)

  # plot size effect
  for(sim in simulations) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary
      # plot
      if(sp == 1) plot(sizex, sizeEffect(sizex, out['DBHopt', 1], out['DBHvar', 1]),
                  type = 'l', ylim = c(0, 1), xlab = 'Size', ylab = 'Size effect',
                  col = spCols[sp],
                  yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)
      points(sizex, sizeEffect(sizex, out['DBHopt', 1], out['DBHvar', 1]), type = 'l', col = spCols[sp])
    }
    mtext(ifelse(sim == 'sim1', sim1name, sim2name), side = 3, line = 0)
    if(sim == 'sim1') mtext("Size effect", 2, las = 0, cex = .8, line = 1.9)
  }

  # plot temp effect
  for(sim in simulations) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary
      # unscale parameters for sim1
      if(sim == 'sim1') {
        scaleInfo <- readRDS(scale[grep(spIds[sp], scale)])
        topt <- unscale(out['T_opt', 1], max = scaleInfo[['mean_TP']][['maxTP3']], min = scaleInfo[['mean_TP']][['minTP3']])
        sigTopt <- unscaleSD(out['sigmaT_opt', 1], max = scaleInfo[['mean_TP']][['maxTP3']], min = scaleInfo[['mean_TP']][['minTP3']])
      }else {
        topt <- out['T_opt', 1]
        sigTopt <- out['sigmaT_opt', 1]
      }

      if(sp == 1) plot(tempx, tempEffect(tempx, topt, sigTopt), type = 'l',
                  ylim = c(0, 1), xlab = 'Temperature', ylab = 'Temperature effect',
                  col = spCols[sp],
                  yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)
      points(tempx, tempEffect(tempx, topt, sigTopt), type = 'l', col = spCols[sp])
    }
    if(sim == 'sim1') mtext("Temperature effect", 2, las = 0, cex = .8, line = 1.9)
  }

  # plot precipitation effect
  for(sim in simulations) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary
      # unscale parameters for sim1
      if(sim == 'sim1') {
        scaleInfo <- readRDS(scale[grep(spIds[sp], scale)])
        popt <- unscale(out['P_opt', 1], max = scaleInfo[['tot_PP']][['maxPP3']], min = scaleInfo[['tot_PP']][['minPP3']])
        sigPopt <- unscaleSD(out['sigmaP_opt', 1], max = scaleInfo[['tot_PP']][['maxPP3']], min = scaleInfo[['tot_PP']][['minPP3']])
      }else {
        popt <- out['P_opt', 1]
        sigPopt <- out['sigmaP_opt', 1]
      }

      if(sp == 1) plot(precx, precEffect(precx, popt, sigPopt), type = 'l',
                  ylim = c(0, 1), xlab = 'Precipiation', ylab = 'Precipiation effect',
                  col = spCols[sp],
                  yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)
      points(precx, precEffect(precx, popt, sigPopt), type = 'l', col = spCols[sp])
    }
    if(sim == 'sim1') mtext("Precipiation effect", 2, las = 0, cex = .8, line = 1.9)
  }

  # plot canopy effect
  for(sim in simulations) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary

      if(sp == 1) plot(c(0, 1), c(compEffect(0, out['beta', 1]), 1), xlim = c(-.5, 1.5),
      ylim = c(0, 1), pch = 8, xlab = 'Canopy status', ylab = 'Competition effect',
      col = spCols[sp],
      yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)

      points(0, compEffect(0, out['beta', 1]), pch = 8, col = spCols[sp])
    }
    if(sim == 'sim1') mtext("Competition effect", 2, las = 0, cex = .8, line = 1.9)
  }
  legend('bottomright', legend = spIds, col = spCols, lty = 1, bty = 'n', cex = 0.9)
```



# Predictions

```{r, echo = F}
# Plot predictions
  # define model

  mort_model <- function(param, newdata) {
    lgPart <- (log(newdata$D/param["DBHopt"])/param["DBHvar"])^2

    mort <- 1 / (1 + (param["psi"] * (newdata$CS + (1 - newdata$CS) * param["beta"]) *
                exp(-0.5*(newdata$TP - param["T_opt"])^2/param["sigmaT_opt"]^2) *
                exp(-0.5*(newdata$PP - param["P_opt"])^2/param["sigmaP_opt"]^2) *
                exp(-lgPart)))
    mort_df <- cbind(mort, newdata)
  }

  # data frame with fixed data to run the model
  # Temp
  newdataT <- data.frame(expand.grid(CS = 1,
                                     TP = seq(-30, 20, length.out = 200),
                                     PP = 1150,
                                     D = c(100, 300, 500)))
  # Prec
  newdataP <- data.frame(expand.grid(CS = 1,
                                     TP = 1.5,
                                     PP = seq(200, 2500, length.out = 200),
                                     D = c(100, 300, 500)))
  # Size
  newdataD <- data.frame(expand.grid(CS = 1,
                                     TP = 1.5,
                                     PP = 1150,
                                     D = seq(10, 900, length.out = 200)))


  # Function in which you give a rstan output (species_id) and it returns the three plots
  plot_prediction <- function(sim, sp, model, data) {

    # Prepare data
    newdataT <- data[['newdataT']]
    newdataP <- data[['newdataP']]
    newdataD <- data[['newdataD']]

    # simulation
    fit <- get(paste('fit', sim, sp, sep = '_'))

    # posterior distribution
    posterior <- rstan::extract(fit)

    param_summary <- summary(fit, probs = c(0.1, 0.9))$summary
    rownames(param_summary) <- names(posterior)
    param_summary <- param_summary[,-c(2:3)]

    # Unscale T_opt & P_opt
    if(sim == 'sim1') {

      # load scale info
      si <- readRDS(scale[grep(sp, scale)])

      param_summary[2,1:3] <- unscale(param_summary[2,1:3], max = si[['mean_TP']][['maxTP3']], min = si[['mean_TP']][['minTP3']])
      param_summary[3,1:3] <- unscaleSD(param_summary[3,1:3], max = si[['mean_TP']][['maxTP3']], min = si[['mean_TP']][['minTP3']])

      param_summary[4,1:3] <- unscale(param_summary[4,1:3], max = si[['tot_PP']][['maxPP3']], min = si[['tot_PP']][['minPP3']])
      param_summary[5,1:3] <- unscaleSD(param_summary[5,1:3], max = si[['tot_PP']][['maxPP3']], min = si[['tot_PP']][['minPP3']])

    }

    # define parameters
    param_mean <- param_summary[-10, 1]
    param_ci10 <- param_summary[-10, 2]
    param_ci90 <- param_summary[-10, 3]

    # get predictions
    mort_meanT <- mort_model(param = param_mean, newdata = newdataT)
    mort_ci10T <- mort_model(param = param_ci10, newdata = newdataT)
    mort_ci90T <- mort_model(param = param_ci90, newdata = newdataT)

    mort_meanP <- mort_model(param = param_mean, newdata = newdataP)
    mort_ci10P <- mort_model(param = param_ci10, newdata = newdataP)
    mort_ci90P <- mort_model(param = param_ci90, newdata = newdataP)

    mort_meanD <- mort_model(param = param_mean, newdata = newdataD)
    mort_ci10D <- mort_model(param = param_ci10, newdata = newdataD)
    mort_ci90D <- mort_model(param = param_ci90, newdata = newdataD)

    size2plot <- unique(newdataT$D)
    colsize <- rev(RColorBrewer::brewer.pal(length(size2plot) + 1, "PuBuGn"))

    if(sim == 'sim1')
      par(mfcol = c(3, 2), xaxs="i", las = 1, mar = c(3, 1, 3, 1.5), oma = c(1,3.5,2,.2), mgp = c(1.5, 0.3, 0), tck = -.008, cex.lab = 1.2, cex.axis = 1.2)

    # Mortality vs temperature
    plot(mort ~ TP, mort_ci10T, type = "n", ylim = c(0, 1),
         xlab = "Temperature (°C)", ylab = "", cex.lab = 1.2, yaxt = ifelse(sim == 'sim1', "s", "n"))
    if(sim == 'sim2') axis(2,labels=F)

    for(dhp in size2plot) {
      mu <- subset(mort_meanT, D==dhp)
      ci10 <- subset(mort_ci10T, D==dhp)
      ci90 <- subset(mort_ci90T, D==dhp)
      mycol <- colsize[size2plot==dhp]

      lines(mort ~ TP, mu, cex=.5, pch=19, col = mycol)
      polygon(c(mu$TP, rev(mu$TP)),
              c(ci10$mort, rev(ci90$mort)),
              col = alpha(mycol, 0.5), border = NA)
    }
    if(sim == 'sim1')
      legend("topleft", legend=size2plot, title = "Tree DHP",
             fill = colsize[1:3], bty = "n", border = "transparent")

     mtext(ifelse(sim == 'sim1', sim1name, sim2name), side = 3, line = 0)
     mtext(sp, side = 3, outer = TRUE, cex = 1, line = -2)

    # Mortality vs precipitation
    plot(mort ~ PP, mort_ci10P, type = "n", ylim = c(0, 1),
         xlab = "Precipiation (mm)", ylab = " ", yaxt = ifelse(sim == 'sim1', "s", "n"), cex.lab = 1.2)
    axis(2,labels=F)
    for(dhp in size2plot) {
      mu <- subset(mort_meanP, D==dhp)
      ci10 <- subset(mort_ci10P, D==dhp)
      ci90 <- subset(mort_ci90P, D==dhp)
      mycol <- colsize[size2plot==dhp]

      lines(mort ~ PP, mu, cex=.5, pch=19, col = mycol)
      polygon(c(mu$PP, rev(mu$PP)),
              c(ci10$mort, rev(ci90$mort)),
              col = alpha(mycol, 0.5), border = NA)
    }
    mtext("P(Mortality)", 2, outer = T, las = 0, cex = .8, line = 1.5)

    # Mortality vs size
    plot(mort ~ D, mort_ci10D, type = "n", ylim = c(0, 1),
         xlab = "DHP (mm)", ylab = "", yaxt = ifelse(sim == 'sim1', "s", "n"), cex.lab = 1.2)
    axis(2,labels=F)
    lines(mort ~ D, mort_meanD, cex=.5, pch=19, col = "grey25")
    polygon(c(mort_meanD$D, rev(mort_meanD$D)),
              c(mort_ci10D$mort, rev(mort_ci90D$mort)),
              col = alpha("grey25", 0.1), border = NA)

  }
  ```

  ```{r plot predictions,echo=FALSE,fig.height = 11, fig.width = 9}
  # plot all species
  for(sp in spIds) {
    for(sim in simulations) {
      plot_prediction(sim, sp, mort_model,
      data = list(newdataT = newdataT, newdataP = newdataP, newdataD = newdataD))
    }
  }
  #
#
```



# Sampling time

```{r sampling time, echo = FALSE}

samplingDF <- data.frame()

for(sim in simulations) {
  for(sp in spIds) {
    simName <- paste('fit', sim, sp, sep = '_')
    sumTime <- rowSums(get_elapsed_time(get(simName)))
    nChain <- length(sumTime)
    df1 <- data.frame(sim = rep(sim, nChain),
                     sp = rep(sp, nChain),
                     time = sumTime)
    samplingDF <- rbind(samplingDF, df1)
  }
}

samplingDF$time <- samplingDF$time/60/60
```

```{r plot sampling time, echo = FALSE, fig.height = 6, fig.width = 12}

p <- ggplot(data = samplingDF, aes(x = sim, y = time)) +
      geom_boxplot() +
      #coord_flip() +
      facet_grid(~sp,
                labeller = labeller(sim = setNames(c(sim1name,
                                    sim2name),
                                    c('sim1', 'sim2')))) +
      theme_classic() +
      ylab('Time (h)')
print(p)
```
