---
 title: "MCMC diagnostics - Growth"
 subtitle: "Test v1.0 - Basic growth"
 author: "Will Vieira"
 date: "`r paste('Last updated on', format(Sys.time(), '%d %B, %Y'))`"
---


## Compare the convergence of the model using two different variables to predict the competition effect:

- **sim1**: canopyDistance
- **sim2**: Basal area (BA)

```{r, echo = F}
suppressPackageStartupMessages(library(rstan))
suppressPackageStartupMessages(require(RColorBrewer))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggpubr))
suppressPackageStartupMessages(library(ggridges))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(data.table))
```
```{r load simulations, echo = F}
# Load simulation variables
  simInfo <- yaml::read_yaml('_simulation_info.yml')

  # species id
  if(is.null(simInfo$spIds)) {
    spIds <- readRDS('data/spIds.RDS')
  }else {
    spIds <- simInfo$spIds
  }

  simName <- simInfo$simName

  simulations <- simInfo$simulations

  # Human readble simName
  sim1name <- 'canopyDistance'
  sim2name <- 'Basal area'

#


# Load rStan output and scaleInfo for all species_id
  # get output name for each species_id
  simNames = list.files(path = paste('output', simName, sep = '/'), pattern = '.RDS', recursive = TRUE, full.names = TRUE)
  output = simNames[grep('growthMCMC', simNames)]

  for(sim in simulations) {
    for(sp in spIds) {
      fileName <- output[grep(paste0(sim, sp), output)]
      assign(paste('fit', sim, sp, sep = '_'), readRDS(fileName))
    }
  }

  # get name of parameters for each simulation
  for(sim in simulations)
  {
    # get one MCMC file for a specific sim
    assign(paste0('pars_', sim), rownames(summary(get(ls(pattern = sim)[1]))[[1]]))
  }

#

###########################################
# Diagnostics
###########################################
```



# Rhat

```{r, echo = F, fig.height = 6, fig.width = 10}

  # number of parameters for all simulations
  nbParams <- prod(unlist(lapply(as.list(paste0('pars_', simulations)), function(x) length(get(x)))))
  # create a table with Rhat for each parameter (clumn) and species_id (Rhat)
  Rhat <- data.frame()
  count = 1
  for(sim in simulations) {
    for(sp  in spIds) {
      df <- summary(get(paste('fit', sim, sp, sep = '_')))$summary
      nRow = nrow(df)
      dfToAdd <- data.frame(rep(sim, nRow), rep(sp, nRow), rownames(df), df[, 'Rhat'], row.names = NULL)
      Rhat <- rbind(Rhat ,dfToAdd)
    }
  }
  names(Rhat) <- c('sim', 'sp', 'pars', 'Rhat')

  p <- ggplot(data = Rhat, aes(x = sp, y = Rhat)) +
       geom_boxplot() +
       coord_flip() +
       facet_grid(~sim, scales = 'free_x',
                 labeller = labeller(sim = setNames(c(sim1name, sim2name),
                                     c('sim1', 'sim2'
                                    )))) +
       theme_classic()
  print(p)
```



# Divergent transitions

```{r divergent transitions, echo = FALSE}

divergentDF <- data.frame(matrix(NA, ncol = 3))
names(divergentDF) <- c('sim', 'sp', 'divergent')

count = 1
for(sim in simulations) {
  for(sp in spIds) {
    simNames <- paste('fit', sim, sp, sep = '_')
    sampler_params <- get_sampler_params(get(simNames), inc_warmup = FALSE)
    nbDivergent <- sum(unlist(lapply(sampler_params, function(mat) mat[, 'divergent__'])))
    divergentDF[count, ] <- c(sim, sp, nbDivergent)
    count = count + 1
  }
}
```

```{r divergent table, echo = FALSE}
DT::datatable(divergentDF)
```



# Density plot of each parameter by species id

```{r get MCMC sampling data, echo = F}
  # Prepare data
  # Data frame with sim, sp_id, pars and value
  # Value is all MCMC samples after warmup for all chains together

  mcmcSampleDF <- data.frame()
  for(sim in simulations) {
    for(sp in spIds) {
      simObj <- get(paste('fit', sim, sp, sep = '_'))
      dfToAdd <- gather(as.data.frame(simObj), key = 'pars')
      dfToAdd <- cbind(data.frame(sim = rep(sim, nrow(dfToAdd)), sp = rep(sp, nrow(dfToAdd))), dfToAdd)
      mcmcSampleDF <- rbind(mcmcSampleDF, dfToAdd)
    }
  }
```

```{r plot mcmcSample by pars, echo = F, message=FALSE, fig.height = 7, fig.width = 9}

  for(par in unique(mcmcSampleDF$pars))
  {
    p <- ggplot(data = subset(mcmcSampleDF, pars == par), aes(value, sp)) +
         geom_density_ridges_gradient() +
         facet_grid(~sim, scales = 'fixed',
                   labeller = labeller(sim = setNames(c(sim1name, sim2name),
                                       c('sim1', 'sim2')))) +
         theme_classic() +
         xlab(par)
    print(p)
  }
```

# Data distribution

```{r organize data, echo = FALSE}
growth_dt <- readRDS('data/quebec/growth_dt.RDS')
growth_dt <- growth_dt[sp_code2 %in% spIds]
growth_dt <- growth_dt[, .(sp_code2, growth, dbh0, value5_bio60_01, value5_bio60_12, canopyDistance, BA)]

# transform dt
growth <- tidyr::gather(data = growth_dt,
            growth, dbh0, value5_bio60_01, value5_bio60_12, canopyDistance, BA,
            key = 'var', value = 'value')
```

```{r plot data distribution, echo = FALSE, message=FALSE, fig.height = 7, fig.width = 10}
p <- ggplot(data = growth, aes(value, sp_code2)) +
      geom_density_ridges_gradient() +
      facet_grid(~var, scales = 'free_x') + #,
      #          labeller = labeller(sim = setNames(c(sim1name,
      #                              sim2name),
      #                              c('sim1', 'sim2')))) +
      theme_classic()
print(p)
```


# Size, temperature, precipitation and competition effect

```{r, echo = F, fig.height = 11, fig.width = 9}
# Plot of size, temperature, precipitation and competition effect

  # define functions of the model
    # size effect
    sizeEffect = function(x, Phi_opt, sigmaPhi_opt) {
      lgPart <- (log(x/Phi_opt)/sigmaPhi_opt)^2
      return( exp(-lgPart))
    }

    # temperature effect
    tempEffect = function(xtemp, T_opt, sigmaT_opt) {
      return(0.0001 + exp(-0.5*(xtemp - T_opt)^2/sigmaT_opt^2))
    }

    # precipitation effect
    precEffect = function(xprec, P_opt, sigmaP_opt) {
      return(exp(-0.5*(xprec - P_opt)^2/sigmaP_opt^2))
    }

    # competition effect
    compEffectCanopy = function(xcanopy, Lo, Mid) {
      return( (Lo + ((1 - Lo) / (1 + exp(-0.5 * (xcanopy - Mid))))) )
    }

    compEffectBA = function(xBA, Lo, beta) {
      return( (Lo + ((1 - Lo) / (1 + exp(-beta * (xBA - 20))))) )
    }

  #

  ## PLOT ##

  # define x axis
  sizex = seq(91, 700, 0.5)
  tempx = seq(-8, 25)
  precx = seq(500, 1700)
  canopyDist = seq(-40, 50, length.out = 200)
  BAx = seq(0, 80, 0.1)

  # species specfic colours
  spCols <- rev(RColorBrewer::brewer.pal(length(spIds), "Set3"))

  par(mfrow = c(4, length(simulations)), xaxs = "i", las = 1, mar = c(3, 1, 1.5, 1.5), oma = c(1,3.5,2,.2), mgp = c(1.5, 0.3, 0), tck = -.008, cex.lab = 1.2, cex.axis = 1.2)

  # plot size effect
  for(sim in simulations) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary
      # plot
      if(sp == 1) plot(sizex, sizeEffect(sizex, out['Phi_opt', 1], out['sigmaPhi_opt', 1]),
                  type = 'l', ylim = c(0, 1), xlab = 'Size (mm)', ylab = 'Size effect',
                  col = spCols[sp],
                  yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)
      points(sizex, sizeEffect(sizex, out['Phi_opt', 1], out['sigmaPhi_opt', 1]), type = 'l', col = spCols[sp])
    }
    mtext(ifelse(sim == 'sim1', sim1name, ifelse(sim == 'sim2', sim2name, sim3name)), side = 3, line = 0)
    if(sim == 'sim1') mtext("Size effect", 2, las = 0, cex = .8, line = 1.9)
  }

  # plot temp effect
  for(sim in simulations) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary
      topt <- out['T_opt', 1]
      sigTopt <- out['sigmaT_opt', 1]

      if(sp == 1) plot(tempx, tempEffect(tempx, topt, sigTopt), type = 'l',
                  ylim = c(0, 1), xlab = 'Temperature (°C)', ylab = 'Temperature effect',
                  col = spCols[sp],
                  yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)
      points(tempx, tempEffect(tempx, topt, sigTopt), type = 'l', col = spCols[sp])
    }
    if(sim == 'sim1') mtext("Temperature effect", 2, las = 0, cex = .8, line = 1.9)
  }

  # plot precipitation effect
  for(sim in simulations) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary
      popt <- out['P_opt', 1]
      sigPopt <- out['sigmaP_opt', 1]

      if(sp == 1) plot(precx, precEffect(precx, popt, sigPopt), type = 'l',
                  ylim = c(0, 1), xlab = 'Precipiation (mm)', ylab = 'Precipiation effect',
                  col = spCols[sp],
                  yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)
      points(precx, precEffect(precx, popt, sigPopt), type = 'l', col = spCols[sp])
    }
    if(sim == 'sim1') mtext("Precipiation effect", 2, las = 0, cex = .8, line = 1.9)
  }

  # plot canopyDistance effect
  for(sim in simulations[1]) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary
      Lo <- out['Lo', 1]
      Mid <- out['Mid', 1]

      if(sp == 1) plot(canopyDist, compEffectCanopy(canopyDist, Lo, Mid), xlim = c(-35, 40),
      ylim = c(0, 1), type = 'l', xlab = 'Canopy distance', ylab = 'Competition effect',
      col = spCols[sp],
      yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)

      points(canopyDist, compEffectCanopy(canopyDist, Lo, Mid), type = 'l', col = spCols[sp])
    }

    if(sim == 'sim1') mtext("Competition effect", 2, las = 0, cex = .8, line = 1.9)
  }
  legend('bottomright', legend = spIds, col = spCols, lty = 1, bty = 'n')

  # plot BA effect
  for(sim in simulations[2]) {
    for(sp in 1:length(spIds)) {
      # get parameters
      out <- summary(get(paste('fit', sim, spIds[sp], sep = '_')))$summary
      Lo <- out['Lo', 1]
      beta <- out['beta', 1]

      if(sp == 1) plot(BAx, compEffectBA(BAx, Lo, beta), xlim = c(0, 80),
      ylim = c(0, 1), type = 'l', xlab = 'Canopy distance', ylab = 'Competition effect',
      col = spCols[sp],
      yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2, labels = FALSE)

      points(BAx, compEffectBA(BAx, Lo, beta), type = 'l', col = spCols[sp])
    }

    if(sim == 'sim1') mtext("Competition effect", 2, las = 0, cex = .8, line = 1.9)
  }
```


# Predictions

```{r, echo = F}
# Plot predictions
  # define model

  growth_model <- function(param, sim, newdata, indVar = FALSE)
  {

    lgPart <- (log(newdata$D/param["Phi_opt"])/param["sigmaPhi_opt"])^2

    # competition function depending on simulation
    if(sim == 'sim1') {
      competition <- (param["Lo"] + ((1 - param["Lo"]) / (1 + exp(-0.5 * (newdata$CD - param["Mid"])))))
    }else {
      competition <- (param["Lo"] + ((1 - param["Lo"]) / (1 + exp(-param["beta"] * (newdata$CD - 20)))))
    }

    mu_d <- param["pdg"] *
            competition *
            exp(-0.5*(newdata$TP - param["T_opt"])^2/param["sigmaT_opt"]^2) *
            exp(-0.5*(newdata$PP - param["P_opt"])^2/param["sigmaP_opt"]^2) *
            exp(-lgPart)

    if(!indVar)
    {
      growth <- mu_d
    }else {
      means <- smooth.spline(rgamma(length(mu_d), mu_d^2/param["sigma_base"], mu_d/param["sigma_base"]), spar = 0.2)$y
      means[means < 0] = 0.0001 # mooth generates negative values but gamma dist does not allow negative values
      lower <- qgamma(.95, (means^2/param["sigma_base"]), means/param["sigma_base"], lower.tail = FALSE)
      upper <- qgamma(.95, (means^2/param["sigma_base"]), means/param["sigma_base"])
      growth <- data.frame(means = means, lower = lower, upper = upper)
    }

    return( cbind(growth, newdata) )
  }

  # Function in which you give a rstan output (species_id) and it returns the three plots
  plot_prediction <- function(sim, sp, model, data) {

    # Prepare data
    newdataT <- data[['newdataT']]
    newdataP <- data[['newdataP']]
    newdataD <- data[['newdataD']]
    newdataC <- data[['newdataC']]

    # simulation
    fit <- get(paste('fit', sim, sp, sep = '_'))

    # posterior distribution
    posterior <- rstan::extract(fit)

    param_summary <- summary(fit, probs = c(0.1, 0.9))$summary
    rownames(param_summary) <- names(posterior)
    param_summary <- param_summary[,-c(2:3)]

    # define parameters
    nRow <- nrow(param_summary)
    param_mean <- param_summary[-nRow, 1]
    param_ci10 <- param_summary[-nRow, 2]
    param_ci90 <- param_summary[-nRow, 3]

    cd2plot <- unique(newdataT$CD)
    colcd <- rev(RColorBrewer::brewer.pal(length(cd2plot) + 1, "PuBuGn"))
    colcd_indVar <- rev(RColorBrewer::brewer.pal(length(cd2plot) + 1, "Greens"))

    if(sim == 'sim1')
      par(mfcol = c(4, length(simulations) * 2), xaxs="i", las = 1, mar = c(3, 1, 3, 1.5), oma = c(1,3.5,2,.2), mgp = c(1.5, 0.3, 0), tck = -.008, cex.lab = 1.2, cex.axis = 1.2)

    for(indVar in c(FALSE, TRUE))
    {
      # Growth vs temperature

      # get papredictions
      if(!indVar)
      {
        growth_meanT <- growth_model(param = param_mean, sim = sim, newdata = newdataT)
        growth_ci10T <- growth_model(param = param_ci10, sim = sim, newdata = newdataT)
        growth_ci90T <- growth_model(param = param_ci90, sim = sim, newdata = newdataT)
      }else {
        DF <- growth_model(param = param_mean, sim = sim, newdata = newdataT, indVar = TRUE)
        growth_meanT <- DF[, c(1, 4:7)]
        growth_ci10T <- DF[, c(2, 4:7)]
        growth_ci90T <- DF[, c(3, 4:7)]
        names(growth_meanT)[1] <- names(growth_ci10T)[1] <- names(growth_ci90T)[1] <- 'growth'
      }

      plot(growth ~ TP, growth_ci90T, type = "n", ylim = c(0, 4),
          xlab = "Temperature (°C)", ylab = "", cex.lab = 1.2, yaxt = ifelse(sim == 'sim1', "s", "n"))
      if(sim == 'sim2') axis(2,labels=F)

      for(cd in cd2plot) {
        mu <- subset(growth_meanT, CD == cd)
        ci10 <- subset(growth_ci10T, CD == cd)
        ci90 <- subset(growth_ci90T, CD == cd)
        mycol <- ifelse(indVar, colcd_indVar[cd2plot == cd], colcd[cd2plot == cd])

        lines(growth ~ TP, mu, cex=.5, pch=19, col = mycol)
        polygon(c(mu$TP, rev(mu$TP)),
                c(ci10$growth, rev(ci90$growth)),
                col = alpha(mycol, ifelse(indVar, 0.15, 0.5)), border = NA)
      }
      # add data range
      abline(v = growth_dt[sp_code2 == sp, range(value5_bio60_01)], col = 'grey', lty = 2)

      if(indVar)
      {
        legend("topleft", legend = cd2plot, title = ifelse(sim == 'sim1', "Canopy distance", "Basal area"),
                fill = colcd_indVar[1:3], bty = "n", border = "transparent")
      }else{
        legend("topleft", legend = cd2plot, title = ifelse(sim == 'sim1', "Canopy distance", "Basal area"),
                fill = colcd[1:3], bty = "n", border = "transparent")
      }

      mtext(ifelse(indVar, 'ind variation', 'par variation'), side = 3, line = 0.3, cex = 1)
      if(!indVar) mtext(ifelse(sim == 'sim1', sim1name, ifelse(sim == 'sim2', sim2name, sim3name)), side = 3, line = 0.7, at = max(newdataT$TP), cex = 1.1)
      if(!indVar) mtext(sp, side = 3, outer = TRUE, cex = 1, line = -1.8)

      # Growth vs precipitation

      # get predictions
      if(!indVar)
      {
        growth_meanP <- growth_model(param = param_mean, sim = sim, newdata = newdataP)
        growth_ci10P <- growth_model(param = param_ci10, sim = sim, newdata = newdataP)
        growth_ci90P <- growth_model(param = param_ci90, sim = sim, newdata = newdataP)
      }else {
        DF <- growth_model(param = param_mean, sim = sim, newdata = newdataP, indVar = TRUE)
        growth_meanP <- DF[, c(1, 4:7)]
        growth_ci10P <- DF[, c(2, 4:7)]
        growth_ci90P <- DF[, c(3, 4:7)]
        names(growth_meanP)[1] <- names(growth_ci10P)[1] <- names(growth_ci90P)[1] <- 'growth'
      }

      plot(growth ~ PP, growth_ci90P, type = "n", ylim = c(0, 4),
          xlab = "Precipiation (mm)", ylab = " ", yaxt = ifelse(sim == 'sim1', "s", "n"), cex.lab = 1.2)
      axis(2, labels = F)
      for(cd in cd2plot) {
        mu <- subset(growth_meanP, CD == cd)
        ci10 <- subset(growth_ci10P, CD == cd)
        ci90 <- subset(growth_ci90P, CD == cd)
        mycol <- ifelse(indVar, colcd_indVar[cd2plot == cd], colcd[cd2plot == cd])

        lines(growth ~ PP, mu, cex = .5, pch = 19, col = mycol)
        polygon(c(mu$PP, rev(mu$PP)),
                c(ci10$growth, rev(ci90$growth)),
                col = alpha(mycol, ifelse(indVar, 0.15, 0.5)), border = NA)
      }
      # add data range
      abline(v = growth_dt[sp_code2 == sp, range(value5_bio60_12)], col = 'grey', lty = 2)

      mtext("P(Growth)", 2, outer = T, las = 0, cex = .8, line = 1.5)

      # Growth vs size

      # get predictions
      if(!indVar)
      {
        growth_meanD <- growth_model(param = param_mean, sim = sim, newdata = newdataD)
        growth_ci10D <- growth_model(param = param_ci10, sim = sim, newdata = newdataD)
        growth_ci90D <- growth_model(param = param_ci90, sim = sim, newdata = newdataD)
      }else {
        DF <- growth_model(param = param_mean, sim = sim, newdata = newdataD, indVar = TRUE)
        growth_meanD <- DF[, c(1, 4:7)]
        growth_ci10D <- DF[, c(2, 4:7)]
        growth_ci90D <- DF[, c(3, 4:7)]
        names(growth_meanD)[1] <- names(growth_ci10D)[1] <- names(growth_ci90D)[1] <- 'growth'
      }

      plot(growth ~ D, growth_ci10D, type = "n", ylim = c(0, 4),
          xlab = "Size (mm)", ylab = "", yaxt = ifelse(sim == 'sim1', "s", "n"), cex.lab = 1.2)
      axis(2, labels = F)
      for(cd in cd2plot) {
        mu <- subset(growth_meanD, CD == cd)
        ci10 <- subset(growth_ci10D, CD == cd)
        ci90 <- subset(growth_ci90D, CD == cd)
        mycol <- ifelse(indVar, colcd_indVar[cd2plot == cd], colcd[cd2plot == cd])

        lines(growth ~ D, mu, cex = .5, pch = 19, col = mycol)
        polygon(c(mu$D, rev(mu$D)),
                c(ci10$growth, rev(ci90$growth)),
                col = alpha(mycol, ifelse(indVar, 0.15, 0.5)), border = NA)
      }
      # add data range
      abline(v = growth_dt[sp_code2 == sp, range(dbh0)], col = 'grey', lty = 2)

      # Growth vs canopy

      # get predictions
      if(!indVar)
      {
        growth_meanC <- growth_model(param = param_mean, sim = sim, newdata = newdataC)
        growth_ci10C <- growth_model(param = param_ci10, sim = sim, newdata = newdataC)
        growth_ci90C <- growth_model(param = param_ci90, sim = sim, newdata = newdataC)
      }else {
        DF <- growth_model(param = param_mean, sim = sim, newdata = newdataC, indVar = TRUE)
        growth_meanC <- DF[, c(1, 4:7)]
        growth_ci10C <- DF[, c(2, 4:7)]
        growth_ci90C <- DF[, c(3, 4:7)]
        names(growth_meanC)[1] <- names(growth_ci10C)[1] <- names(growth_ci90C)[1] <- 'growth'
      }

      plot(growth ~ CD, growth_ci10C, type = "n", ylim = c(0, 4),
          xlab = ifelse(sim == 'sim1', "Canopy distance from S* (m)", "Basal area (m²/ha)"), ylab = "", yaxt = ifelse(sim == 'sim1', "s", "n"), cex.lab = 1.2)
      axis(2, labels = F)
      lines(growth ~ CD, growth_meanC, cex = .5, pch = 19, col = mycol)
      polygon(c(growth_meanC$CD, rev(growth_meanC$CD)),
              c(growth_ci10C$growth, rev(growth_ci90C$growth)),
              col = alpha("grey25", 0.1), border = NA)

      # add data range
      if(sim == 'sim1')
      {
        abline(v = growth_dt[sp_code2 == sp, range(canopyDistance)], col = 'grey', lty = 2)
      }else{
        abline(v = growth_dt[sp_code2 == sp, range(BA)], col = 'grey', lty = 2)
      }

    }
  }
  ```

  ```{r plot predictions,echo=FALSE,fig.height = 12, fig.width = 12}
  # plot all species
  for(sp in spIds) {
    for(sim in simulations) {
      # fixed data for prediction depending on competition variable
      if(sim == 'sim1')
      {
        newdataT <- data.frame(expand.grid(CD = c(-10, 0, 10),
                                          TP = seq(-10, 25, length.out = 300),
                                          PP = 1000,
                                          D = 200))
        # Prec
        newdataP <- data.frame(expand.grid(CD = c(-10, 0, 10),
                                          TP = 4,
                                          PP = seq(250, 1800, length.out = 300),
                                          D = 200))
        # Size
        newdataD <- data.frame(expand.grid(CD = c(-10, 0, 10),
                                          TP = 4,
                                          PP = 1000,
                                          D = seq(0, 1200, length.out = 300)))

        # Canopy distance
        newdataC <- data.frame(expand.grid(CD = seq(-35, 40, length.out = 300),
                                          TP = 4,
                                          PP = 1000,
                                          D = 200))
      }else {
        # Temp
        newdataT <- data.frame(expand.grid(CD = c(5, 20, 40),
                                          TP = seq(-10, 25, length.out = 300),
                                          PP = 1000,
                                          D = 200))
        # Prec
        newdataP <- data.frame(expand.grid(CD = c(5, 20, 40),
                                          TP = 4,
                                          PP = seq(250, 1800, length.out = 300),
                                          D = 200))
        # Size
        newdataD <- data.frame(expand.grid(CD = c(5, 20, 40),
                                          TP = 4,
                                          PP = 1000,
                                          D = seq(0, 1200, length.out = 300)))

        # Canopy distance
        newdataC <- data.frame(expand.grid(CD = seq(0, 100, length.out = 300),
                                          TP = 4,
                                          PP = 1000,
                                          D = 200))
      }
      plot_prediction(sim, sp, growth_model,
      data = list(newdataT = newdataT, newdataP = newdataP, newdataD = newdataD, newdataC = newdataC))
    }
  }
  #
#
```

# Out-of-bag predictions

```{r organize data by sp for OOB predictions,echo=FALSE,fig.height = 12, fig.width = 12}
  # create a list of data.table objects for each spIds
  # For each data.table, we will get all rows that were not used in the fitting stan model
  # I have to do it as the sampleIndices where saved when the data frame was already filtered for the specific sp

  oob_list <- list()
  for(sp in spIds)
  {
    # sp specific db
    db <- growth_dt[sp_code2 == sp]

    # load rows used for stan fit
    sampledIndices <- readRDS(paste0('sampleOut/growth_', sp, '.RDS'))

    db <- db[!sampledIndices, ]

    oob_list[[sp]] <- db
  }
```

```{r calculate OOB predictions,echo=FALSE,fig.height = 12, fig.width = 12}

  # growth model
  growth_model2 <- function(param, sim, D, TP, PP, C, BA, indVar = FALSE)
  {

    lgPart <- (log(D/param["Phi_opt"])/param["sigmaPhi_opt"])^2

    # competition function depending on simulation
    if(sim == 'sim1') {
      competition <- (param["Lo"] + ((1 - param["Lo"]) / (1 + exp(-0.5 * (C - param["Mid"])))))
    }else {
      competition <- (param["Lo"] + ((1 - param["Lo"]) / (1 + exp(-param["beta"] * (BA - 20)))))
    }

    mu_d <- param["pdg"] *
            competition *
            exp(-0.5*(TP - param["T_opt"])^2/param["sigmaT_opt"]^2) *
            exp(-0.5*(PP - param["P_opt"])^2/param["sigmaP_opt"]^2) *
            exp(-lgPart)

    if(!indVar)
    {
      growth <- mu_d
    }else {
      means <- smooth.spline(rgamma(length(mu_d), mu_d^2/param["sigma_base"], mu_d/param["sigma_base"]), spar = 0.2)$y
      means[means < 0] = 0.0001 # mooth generates negative values but gamma dist does not allow negative values
      lower <- qgamma(.95, (means^2/param["sigma_base"]), means/param["sigma_base"], lower.tail = FALSE)
      upper <- qgamma(.95, (means^2/param["sigma_base"]), means/param["sigma_base"])
      growth <- list(means = means, lower = lower, upper = upper)
    }

    return( growth )
  }

  for(sp in spIds)
  {
    for(sim in simulations)
    {
      # get params
      fit <- get(paste('fit', sim, sp, sep = '_'))
      posterior <- rstan::extract(fit)

      param_summary <- summary(fit, probs = c(0.1, 0.9))$summary
      rownames(param_summary) <- names(posterior)
      param_summary <- param_summary[, -c(2:3)]

      nRow <- nrow(param_summary)
      param_mean <- param_summary[-nRow, 1]
      param_ci10 <- param_summary[-nRow, 2]
      param_ci90 <- param_summary[-nRow, 3]

      if(sim == 'sim1')
      {
        # get deterministic growth rate
        oob_list[[sp]][, Gdet_mean_sim1 := growth_model2(param = param_mean, sim, D = dbh0, TP = value5_bio60_01, PP = value5_bio60_12, C = canopyDistance, BA = BA, indVar = FALSE)]
        oob_list[[sp]][, Gdet_ci10_sim1 := growth_model2(param = param_ci10, sim, D = dbh0, TP = value5_bio60_01, PP = value5_bio60_12, C = canopyDistance, BA = BA, indVar = FALSE)]
        oob_list[[sp]][, Gdet_ci90_sim1 := growth_model2(param = param_ci90, sim, D = dbh0, TP = value5_bio60_01, PP = value5_bio60_12, C = canopyDistance, BA = BA, indVar = FALSE)]

        # get growth rate with individual variation
        oob_list[[sp]][, c('Gvar_mean_sim1', 'Gvar_ci10_sim1', 'Gvar_ci90_sim1') := growth_model2(param = param_mean, sim, D = dbh0, TP = value5_bio60_01, PP = value5_bio60_12, C = canopyDistance, BA = BA, indVar = TRUE)]
      }else{
          # get deterministic growth rate
        oob_list[[sp]][, Gdet_mean_sim2 := growth_model2(param = param_mean, sim, D = dbh0, TP = value5_bio60_01, PP = value5_bio60_12, C = canopyDistance, BA = BA, indVar = FALSE)]
        oob_list[[sp]][, Gdet_ci10_sim2 := growth_model2(param = param_ci10, sim, D = dbh0, TP = value5_bio60_01, PP = value5_bio60_12, C = canopyDistance, BA = BA, indVar = FALSE)]
        oob_list[[sp]][, Gdet_ci90_sim2 := growth_model2(param = param_ci90, sim, D = dbh0, TP = value5_bio60_01, PP = value5_bio60_12, C = canopyDistance, BA = BA, indVar = FALSE)]

        # get growth rate with individual variation
        oob_list[[sp]][, c('Gvar_mean_sim2', 'Gvar_ci10_sim2', 'Gvar_ci90_sim2') := growth_model2(param = param_mean, sim, D = dbh0, TP = value5_bio60_01, PP = value5_bio60_12, C = canopyDistance, BA = BA, indVar = TRUE)]
      }
    }
  }

  oob_growth <- do.call(rbind, oob_list)
  rm(oob_list, db, sampledIndices)

```

```{r plot OOB predictions,echo=FALSE,fig.height = 8, fig.width = 12}

  for(sp in spIds)
  {
    # axis limites
    xyLim <- oob_growth[sp_code2 == sp, range(growth)]

    par(mfcol = c(2, length(simulations)), xaxs = "i", las = 1, mar = c(4, 4, 1, 1), oma = c(7, 5, 7, .5), mgp = c(1, 2.5, 0), tck = -.008, cex.lab = 4, cex.axis = 4, cex = 0.3)
    for(sim in simulations)
    {
      if(sim == 'sim1') {
        db <- oob_growth[sp_code2 == sp, c(2, 8:13)]
      }else{
        db <- oob_growth[sp_code2 == sp, c(2, 14:19)]
      }
      # sample 10% of data
      db <- db[sample(1:nrow(db), floor(nrow(db) * 0.1))]

      # plot deterministic growth
      plot(db[, c('growth', paste0('Gdet_mean_', sim)), with = FALSE], xlim = c(0, 7), ylim = c(0, 7), pch = 20, col = rgb(0, 0, 0, 0.3), xlab = '', ylab = '', xaxt = 'n', yaxt = ifelse(sim == 'sim1', "s", "n"))
      axis(1, labels = NA)
      abline(0, 1)
      segments(db$growth - 0.01, db[[3]], db$growth + 0.01, db[[3]], col = rgb(0, 0, 0, 0.2))
      segments(db$growth - 0.01, db[[4]], db$growth + 0.01, db[[4]], col = rgb(0, 0, 0, 0.2))
      segments(db$growth , db[[3]], db$growth, db[[4]], col = rgb(0, 0, 0, 0.2)) # vertica
      
      # plot gorwth with individual variation
      plot(db[, c('growth', paste0('Gvar_mean_', sim)), with = FALSE], xlim = c(0, 7), ylim = c(0, 7), col = rgb(0, 0, 0, 0.3), xlab = '', ylab = '', yaxt = ifelse(sim == 'sim1', "s", "n"))
      axis(2, labels = NA)
      abline(0, 1)

      segments(db$growth - 0.01, db[[6]], db$growth + 0.01, db[[6]], col = rgb(0, 0, 0, 0.2))
      segments(db$growth - 0.01, db[[7]], db$growth + 0.01, db[[7]], col = rgb(0, 0, 0, 0.2))
      segments(db$growth , db[[6]], db$growth, db[[7]], col = rgb(0, 0, 0, 0.2)) # vertica
      

      # text
      mtext(sp, 3, outer = TRUE, cex = 1, line = 2.5)
      mtext('Deterministic growth', 3, outer = TRUE, cex = 1, line = -0.5)
      mtext('Ind variable growth', 3, outer = TRUE, cex = 1, line = -60)
      mtext('Growth rate (mm/y)', 1, outer = TRUE, line = 1.3, cex = 1)
      mtext('Predicted growth rate (mm/y)', 2, las = 0, outer = TRUE, line = 2.2, cex = 1)
    }
  }
```

# Sampling time

```{r sampling time, echo = FALSE}
samplingDF <- data.frame()

for(sim in simulations) {
  for(sp in spIds) {
    simNames <- paste('fit', sim, sp, sep = '_')
    sumTime <- rowSums(get_elapsed_time(get(simNames)))
    nChain <- length(sumTime)
    df1 <- data.frame(sim = rep(sim, nChain),
                     sp = rep(sp, nChain),
                     time = sumTime)
    samplingDF <- rbind(samplingDF, df1)
  }
}

samplingDF$time <- samplingDF$time/60/60
```

```{r plot sampling time, echo = FALSE, fig.height = 6, fig.width = 12}

p <- ggplot(data = samplingDF, aes(x = sim, y = time)) +
      geom_boxplot() +
      facet_grid(~sp) +
      theme_classic() +
      ylab('Time (h)')
print(p)
```
```{r plot sampling time2, echo = FALSE, fig.height = 5, fig.width = 6}
p <- ggplot(data = samplingDF, aes(x = sim, y = time)) +
      geom_boxplot() +
      theme_classic() +
      ylab('Time (h)')
print(p)
```
